config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from litreview.pages.views import redirect_root

urlpatterns = [
    path("", redirect_root, name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("users/", include("litreview.users.urls", namespace="users")),
    path("tickets/", include("litreview.tickets.urls", namespace="tickets")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litreview/tickets/urls.py
from django.urls import path
from litreview.tickets.views import ticket_add_view

app_name = "tickets"
urlpatterns = [
    path("add/", view=ticket_add_view, name="add"),
]

litreview/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

litreview/users/urls.py
from django.urls import path
from litreview.users.views import user_detail_view, user_follow_view, user_redirect_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<str:username>/follow/", view=user_follow_view, name="follow"),
]

litreview/pages/models.py
from django.db import models

# Create your models here.

litreview/reviews/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from ..tickets.models import Ticket


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    headline = models.CharField(max_length=128)
    body = models.TextField(max_length=8192, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)

litreview/tickets/models.py
from django.conf import settings
from django.db import models


class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)

litreview/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    name = models.CharField("Nom d'utilisateur", max_length=255, blank=True)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})


class UserFollows(models.Model):
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="following"
    )
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="followed_by",
    )

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = (
            "user",
            "followed_user",
        )

litreview/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):
    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": "Ce nom d'utilisateur est déjà utilisé."}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise ValidationError(self.error_messages["duplicate_username"])

litreview/pages/views.py
from django.shortcuts import redirect


def redirect_root(request):
    return redirect("/accounts/login/")

litreview/reviews/views.py
from django.shortcuts import render

# Create your views here.

litreview/tickets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView

from .models import Ticket


class TicketCreateView(LoginRequiredMixin, CreateView):
    model = Ticket
    fields = ["title", "description", "image"]


ticket_add_view = TicketCreateView.as_view()

litreview/users/views.py
from itertools import chain

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import CharField, Value
from django.urls import reverse
from django.views.generic import DetailView, RedirectView
from litreview.reviews.models import Review
from litreview.tickets.models import Ticket

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        reviews = Review.objects.all().filter(user=self.request.user)
        # returns queryset of reviews
        reviews = reviews.annotate(content_type=Value("REVIEW", CharField()))

        tickets = Ticket.objects.all().filter(user=self.request.user)
        # returns queryset of tickets
        tickets = tickets.annotate(content_type=Value("TICKET", CharField()))

        # combine and sort the two types of posts
        posts = sorted(
            chain(reviews, tickets), key=lambda post: post.time_created, reverse=True
        )

        context["posts"] = posts
        return context


user_detail_view = UserDetailView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},  # type: ignore
        )


user_redirect_view = UserRedirectView.as_view()


class UserFollowView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_follow_view = UserFollowView.as_view()

litreview/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}LITReview{% endblock title %}</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <!-- Bootstrap CSS -->
        {% block css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/logo_litreview.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-center" />&nbsp;LITReview</a>
                {% if user.is_authenticated %}
                <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Flux</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:follow' object.username %}">Abonnements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Me déconnecter</a>
                        </li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </nav>

        {% if messages %}
            <div class="container w-50 p-4">
                <strong>Messages:</strong>
                <ul>
                    {% for message in messages %}
                        <li>{{message}}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% block content %}
        <p>Hello, wolrd!</p>
        {% endblock content %}

        <!-- Bootstrap Bundle with Popper -->
        {% block javascript %}
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        {% endblock javascript %}
    </body>
</html>

litreview/templates/tickets/ticket_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Créer un ticket</h1>
    <form class="login" method="POST" action="{% url 'tickets:add' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Créer</button>
    </form>
</div>
{% endblock content %}

litreview/templates/tickets/ticket_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<h1>Liste des tickets</h1>
<ul>
{% for ticket in ticket_list %}
    <li>{{ticket.title}}</li>
{% endfor %}
</ul>
</div>
{% endblock content %}

litreview/templates/users/snippets/review_snippet.html
<div class="card text-white bg-secondary text-center m-2">
    <div class="card-header">
        Vous avez publié une critique
    </div>
    <div class="card-body">
        <h5 class="card-title">{{post.headline}} - {{post.rating}}</h5>
        <p class="card-text">{{post.body}}</p>
        <p class="card-text">
            <div class="card text-black text-center">
                <div class="card-header">
                    Critique demandée par {{post.ticket.user}}
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{post.ticket.title}}</h5>
                    <p class="card-text">{{post.ticket.description}}</p>
                </div>
                <div class="card-footer text-muted">
                    {{post.ticket.time_created}}
                </div>
            </div>
        </p>
    </div>
    <div class="card-footer text-white-50">
        {{post.time_created}}
    </div>
</div>

litreview/templates/users/snippets/ticket_snippet.html
<div class="card text-center m-2">
    <div class="card-header">
        Critique demandée par {{post.user}}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>
        <p class="card-text">{{post.description}}</p>
    </div>
    <div class="card-footer text-muted">
        {{post.time_created}}
    </div>
</div>

litreview/templates/users/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Utilisateur : {{object.username}}{% endblock title %}

{% block content %}
<div class="container w-50 p-4">
    {% if object.username %}
        <h1>Bonjour, {{object.username}} !</h1>
    {% endif %}
    <div class="row justify-content-evenly p-4">
        <div class="col-4">
            <a class="btn btn-primary" href="{% url 'tickets:add' object.username %}">Demander une critique</a>
        </div>
        <div class="col-4">
            <a class="btn btn-primary" href="">Créer une critique</a>
        </div>
    </div>
    <p class="p-4">Voici votre flux d'activités :</p>

        {% for post in posts %}
            {% if post.content_type == 'TICKET' %}
                {% include 'users/snippets/ticket_snippet.html' %}
            {% elif post.content_type == 'REVIEW' %}
                {% include 'users/snippets/review_snippet.html' %}
            {% endif %}
        {% endfor %}

</div>
{% endblock content %}